name: smart_routine
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_local_notifications: ^13.0.0
  # Removed charts_flutter due to compatibility issues
  intl: ^0.17.0  # Version compatible avec charts_flutter 0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
